# Generated by Django 4.0.3 on 2022-06-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='href',
            new_name='bin_href',
        ),
    ]
