# Generated by Django 4.0.3 on 2022-06-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_rename_href_binvo_bin_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='bin_href',
            new_name='href',
        ),
    ]
